### PR TITLE
added private API for debugging virtualization framework

### PR DESCRIPTION
**Pull request by Code-Hex**
Added private API to debug virtualization framework

See how to use this: https://github.com/Code-Hex/vz/wiki/How-to-debug-virtualization-framework

Relates: https://github.com/Code-Hex/vz/issues/59

### CODE REVIEW

**Comment by Code-Hex** [comment]
This API is necessary to check the kernel actually works fine.

**Comment by cfergeau** [comment]
For what it's worth, more details regarding step 7 in https://github.com/Code-Hex/vz/wiki/How-to-debug-virtualization-framework would be useful. Can https://elinux.org/Debugging_The_Linux_Kernel_Using_Gdb be used? Or are there some virtualization framework specific steps to know of?

**Comment by Code-Hex** [comment]
@cfergeau I added a few details to the wiki page but I don't have knowledge about debugging the kernel.
I confirmed that it worked, but I didn't know how to debug it, so I needed to learn more...

**Comment by cfergeau** [comment]
> @cfergeau I added a few details to the wiki page but I don't have knowledge about debugging the kernel. I confirmed that it worked, but I didn't know how to debug it, so I needed to learn more...

The added instructions are helpful, I'll give it a try!

> You can edit the wiki page from now!

Thanks :)

**Pull request merged**
